name: destini_challenge_starting
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"  # Dart SDK sürümünü null safety uyumlu hale getirdik

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  # Buradaki sürümü en son sürümle güncelledik

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/  # Eğer projede asset kullanıyorsanız bu şekilde tanımlayın
